### ISSUE TITLE
make error 

### ISSUE THREAD

**Issue by huangxiaogua** [iric-soft/nektar#1]
hello

    Our team were intrested in your new method, so we tried to install your software nektar.But we met some problems when we renamed the Makefile.linux with Makefile and then execute make the error was as followings
`(env_py2) jm@jm:~/Downloads/nektar-master/nektar_cpp$ make
g++ -c  kmer_assembly.cc
In file included from /home/jm/miniconda2/envs/env_py2/gcc/include/c++/array:35:0,
                 from kmer_assembly.cc:9:
/home/jm/miniconda2/envs/env_py2/gcc/include/c++/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from kmer_assembly.cc:18:0:
/home/jm/miniconda2/envs/env_name/lib/R/library/BH/include/boost/graph/graph_traits.hpp:13:28: fatal error: boost/config.hpp: No such file or directory
 #include <boost/config.hpp>
                            ^
compilation terminated.
Makefile:14: recipe for target 'kmer_assembly.o' failed
make: *** [kmer_assembly.o] Error 1`

can you tell us where is wrong ? thanks

**Comment by huangxiaogua** [comment]
I have installed kmer_assembly by pre-installing boost

**Comment by ericloud** [comment]
Hello, 

Thank for your feedback.

Best,
Eric
