### ISSUE TITLE
Input file and format

### ISSUE THREAD

**Issue by hujingchu** [iric-soft/nektar#2]
Hi,
Could you please specify the input file format of kmer_assembly.
I try the following command but failed:
`kmer_assembly -k test.fa -o test.res  -p test.csv`
which test.fa is a FASTA file from jellyfish dump, test.csv is：
```
SAMPLE  KMER    FORMAT
ttt     221405      FASTA 
```
which report error like:
```
Read args
Read project
Read kmer
221405 kmers read
Time : 0.632114
Create graph assembly
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 10)
Aborted (core dumped)
```
could you please specify the correct input format? thanks a lot.

**Comment by jplaverdure** [comment]
Hello,

When I use it, here are examples of the file contents:
Project File (-p):
```
SAMPLE  JF      GROUP
14H124  14H124.trim.R1rc.33.jf  Ref
```
(although I believe @ericloud removed the need to provide a project file, so you could omit it.)

Kmer file (-k):
```
kmer    14H124
GTTTCCTTCTACAGCATGTCAGCATCTCAAGTT       101
CTGATTCTCCAAGATTCCCTCATAGAGGAATTT       4
ATTGCAGAATACCAGCGTGTATTGCAGGAGAAC       6
```
The kmer file is not a fasta file but really a dump of the jellyfish file of which I only keep 2 columns, the kmer itself and the count of said kmer in the sample.

The dump can be generated using the `jellyfish dump` command.
example call:
`jellyfish dump -c -t -o OUTPUT_FILE JELLYFISH_FILE`

I then extract the relevant columns from the obtained file using:
`cut -f2-3 OUTPUT_FILE > PROJECT_FILE`

I hope this helps !
