### ISSUE TITLE
Linear assembly

### ISSUE THREAD

**Issue by nellykan** [iric-soft/nektar#4]
Hi! If I understand correctly, nektar's default assembly method is the shortest path of the graph but in the code I see also a function for linear assembly. 
How can I use nektar for linear assembly?

**Comment by ericloud** [comment]
Hi Nelly, 

kmer_assembly create a graph where each node is a "local linear assembly".
This graph can be used for more, but in this version we only output each node as you can see in _linear_assembly_ function.

Regards,
Eric.

**Comment by nellykan** [comment]
I see. Thank you!
