### ISSUE TITLE
Short contigs

### ISSUE THREAD

**Issue by arafmahmud** [iric-soft/nektar#7]
I am trying to use Nektar for assembling kmers, generated by Jellyfish from transcriptome reads, with a kmer size of 33.

However, I've encountered a problem where the resulting contig sizes are smaller than expected. Below are the statistics of the assembled contigs:

File: assembly.fasta
Format: FASTA
Type: DNA
Num_seqs: 4,706,715
Sum_len: 161,597,076
Min_len: 33
Avg_len: 34.3
Max_len: 87

I've double-checked my processes and can't seem to identify any steps that I might have missed, so I'm wondering if there are specific parameters or settings I could adjust to improve the assembly process and get larger contigs.

Any guidance would be appreciated. Thanks in advance!

**Comment by ericloud** [comment]
Hi, 

Nektar perform a very basic assembly, he is design to stop the assembly when a contig can be extend by more than one kmer.
This append when we work on low complexity or repeat regions longest than kmer size.

Here I see two choices:
 - increase the size of your kmers and expect that longer kmers reduce the number of "ambigous case" to create longest contig.
 - use an other software based on De Bruijn graph, like [Reindeer](https://github.com/kamimrcht/REINDEER)

Eric.
